import { createApp } from "vue";
import App from "./App.vue";
import router from "@/router/index";
import store from "@/store/index";
import { useElementPlus } from "@/plugin/index";
import "./styles/index.scss";
const app = createApp(App);
app.use(router).use(store);
useElementPlus(app);
app.mount("#app");
